name: Auto release tag

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.head_ref, 'feature/front')
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js v10
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: yarn install, build, and test
        run: |
          yarn install
          yarn export
        env:
          CI: true
      - name: zip output
        run: |
          zip -r files out

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          files: files.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
